name: ia_chat
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  http: ^1.3.0
  flutter_markdown: ^0.6.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true